export const companies = [
    "Oogle",
    "Y: Formerly known as Glitter",
    "Solutions 3",
    "Tech Smart",
    "CompuStart",
    "upLoad",
    "Job Tech",
    "BookFace",
    "Digital Marketing Inc.",
    "Code Mach",
    "Sense Wave",
    "CryptoLogic",
    "Pandalytics",
    "Shark Tech",
    "Data Dolphin",
    "Audio Vision",
    "Cool Breeze Technologies",
    "Shark Fin Marketing Agency",
    "Dino Logic Corporation",
    "TechFiend",
    "Source Volt",
    "Insomniac Tech",
    "Urban AI",
    "SourceCode",
    "Lightning Bolt",
    "JetRains",
    "TerminalTrend",
    "App Droid",
    "DevelopIt",
    "Invison Chip",
    "EduCheck",
    "Speed Sys",
    "Codable",
    "Cryptokenize",
    "SmartTech",
    "Insane Systems",
    "Dymatize",
    "Neurogenic",
    "API Monkey",
    "Solar Nexus",
    "Quest Owl",
    "IcoNiC",
    "StartupFox",
    "bravOS",
    "EZ Bit",
    "Quantum AI",
    "Logistics Incorporated",
    "Atlantic Forest",
    "Orange Inc",
    "MovieStreamz",
    "DigiWave",
]